Returned null in case of empty cookie value
salesforce/tough-cookie pull request #196
Opened 2020-06-17 20:55 UTC by vsin12

1. some of the old sites by mistake send a blank cookie, and whenever a blank cookie is encountered, failed to parse cookie error comes up - so I made a fix of checking the length and accordingly calling callback with null value.

Note: Either this fix, or CookieJar constructor needs to take SetCookieOptions too, as ignoreError is part of SetCookieOptions interface

2020-08-24 21:14 UTC, ruoho commented
Hi @vsin12, would you be able to update the PR with a test?

2020-08-24 21:18 UTC, vsin12 commented
@ruoho : Sorry, but I didn't get you ? Do you want me to give a scenario while it was breaking or you want me to write a test to check my pr ?

2020-09-10 18:04 UTC, awaterma requested changes
You wrote: `Note: Either this fix, or CookieJar constructor needs to take SetCookieOptions too, as ignoreError is part of SetCookieOptions interface`

ignoreError doesn't apply to storage: `ignoreError - boolean - default false - silently ignore things like parse errors and invalid domains. Store errors aren't ignored by this option` -- so I'm not sure we need to do any more here, in terms of implementation. We might want to start a project to review ignoreError and its applications --- it might be better to have that apply globally, but we'd have to think that through.

**In terms of this P/R; I think I'd like to see the change use validators, as suggested, and then have a simple unit test added that demonstrates the use-case (an empty cookie).**

2020-09-10 18:05 UTC, awaterma commented on lib/cookie.js
>      validators.validate(validators.isFunction(cb), cb);
Meaning line 1103/1106 `validators.validate(validators.isFunction(cb), cb);`

2020-10-20 22:25 UTC, awaterma commented
I think we still need a unit test for this fix. :)

2020-11-23 20:41 UTC, medelibero-sfdc commented
@vsin12 can you change this PR to allow edits from maintainers? I have a few changes I would like to push to this PR.

2020-11-23 23:32 UTC, vsin12 commented
> @vsin12 can you change this PR to allow edits from maintainers? I have a few changes I would like to push to this PR.

Done.

2021-01-25 18:51 UTC, awaterma reviewed
I'll discuss this today; I think we want to add a suggestion to return an error when presented with an empty cookie.

2021-01-25 18:51 UTC, awaterma commented on lib/cookie.js
> +
Just looked at this in context, and I think this is fine. Will discuss today.

2021-01-25 18:51 UTC, awaterma commented on test/cookie_jar_test.js
> +        "results in a error being returned because of missing parameters": function(err, cookies) {
We don't actually return an error, we are invoking the callback with a Null here. Should we invoke the CB with an Error()?

2021-01-25 18:51 UTC, awaterma commented on lib/cookie.js
> +
Please see comment below; I think we may want an Error here.

2021-02-16 22:08 UTC, awaterma approved these changes
Approved. We may want to add error checking/throwing at some point, but that's probably in a major release.

2021-02-16 22:08 UTC, merged

2026-01-05 16:53 UTC, navagj0 commented on lib/cookie.js
> +
#413 bump the dev format