Enable strict type checked rules
salesforce/tough-cookie pull request #392
Opened 2024-03-21 21:04 UTC by wjhsf

When doing #383, I noticed that we extend `@typescript-eslint/recommended-type-checked` and `@typescript-eslint/strict`. There's also `@typescript-eslint/strict-type-checked` which is includes those two configs, plus a few additional type checked rules.

I also moved us from `.eslintrc` to the new flat config, just because we can!

2024-03-21 21:06 UTC, wjhsf commented on package.json
> +    "lint": "eslint .",
Because every other project I work on uses `lint`, not `eslint`.

2024-03-22 12:23 UTC, colincasey requested changes
@wjhsf not sure what's going on with this PR but I tried to work around the bad resolutions in `package-lock.json` by just deleting and regenerating it locally with a fresh `npm install`. But, after doing that, I get errors when I execute `npm run lint` that `eslint-config-prettier` cannot be found.

2024-03-22 12:23 UTC, colincasey commented on package-lock.json
@wjhsf there are some nexus resolutions in this package.json that prevent it from being usable

2024-03-22 15:19 UTC, wjhsf commented on package-lock.json
🫠

2024-03-22 20:10 UTC, colincasey commented
@wjhsf I'm not so sure about these changes. If you check the test output of https://github.com/salesforce/tough-cookie/actions/runs/8392570051/job/22985505761?pr=392 it looks like there are regressions introduced with the vows test suite which we're using as a sanity check for these types of refactorings. 

Maybe a better approach is to disable all the new rules introduced with `@typescript-eslint/strict-type-checked` and have incremental PRs with each rule enabled + it's required changes?

2024-04-22 14:35 UTC, wjhsf commented
Since we don't super care about how clean the vows tests are, I've just disabled the violated rules instead of fixing them, except one violation that's trivial.

2024-04-26 17:56 UTC, colincasey commented on eslint.config.mjs
> +      'max-lines': ['warn', 500],
I ended up bumping this to `2000` after the tsdocs where introduced in #384. Should we just disable this rule entirely?

 ```suggestion
      'max-lines': ['warn', 2000],
```

2024-05-07 12:04 UTC, colincasey approved these changes

2024-05-07 14:31 UTC, merged